### ISSUE TITLE
Add upspin server availing scans

### ISSUE THREAD

**Issue by stapelberg** [stapelberg/scan2drive#14]

**Comment by stapelberg** [comment]
This guide assumes you already know what upspin is and have used it successfully.

## Create a new upspin user for scan2drive

Generate a separate keypair for the new user:
```
upspin keygen $HOME/upspin-scan2drive
```
Get the current user file and modify it for the new user (change name and remotes, replace publickey with the contents from `$HOME/upspin-scan2drive/public.upspinkey`):
```
% upspin user > /tmp/user
% $EDITOR /tmp/user
% cat /tmp/user
name: michael+scan2drive@stapelberg.invalid
dirs:
- remote,scan2drive.zekjur.net:443
stores:
- remote,scan2drive.zekjur.net:443
publickey: |
  p256
  102031428936418181005193899366010813928674804949401884683801190053837718845690
  62751216777725468126825714892230146462554796332409809564370844821318091796916
```

Then upload the new (suffixed) user using the current user’s credentials
```
% upspin user -put michael+scan2drive@stapelberg.invalid < /tmp/user
```

## Create a new config file

```
% cat > $HOME/upspin-scan2drive/config <<'EOT'
username: michael+scan2drive@stapelberg.invalid
secrets: /perm/upspin-config/
storeserver: remote,scan2drive.zekjur.net:443
dirserver: remote,scan2drive.zekjur.net:443
packing: ee
cmdflags:
  s2dup:
    addr: scan2drive.zekjur.net:443
    letscache: /perm/letscache/
EOT
```

## Copy the configuration to your persistent data partition

```
% sudo mount /dev/sdb4 /perm
% sudo mkdir /perm/upspin-config
% sudo cp $HOME/upspin-scan2drive/* /perm/upspin-config/
```

Grant access to the scans to your main upspin user:
```
% echo "Read,List: michael@stapelberg.invalid" | sudo tee /perm/scans/Access
```

Unmount the persistent data partition:
```
% sudo umount /perm
```

## Install s2d-up

```
% gokr-packer -overwrite=/dev/sdb github.com/stapelberg/scan2drive github.com/stapelberg/scan2drive/cmd/s2d-up
```

…and put the SD card back into the Raspberry Pi.

Once the Raspberry Pi has booted, you should be able to use `upspin ls michael+scan2drive@stapelberg.invalid` to see your scans.
